---
title       : Statistics 101
subtitle    : Deciding what on Statistic test choose
author      : Tuhin Mahmud
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
--- 

## Varible types 
1. Interval
2. Categorical
3. Ordinal


--- 

## Assumptions of data and sampling distribution

1. Normality assumption

2. Homogeneity of Variance 

3. Independence of sample

---

## Input and Output variables

```{r echo=FALSE,message=FALSE}
require("googleVis")
 setwd("C:/Users/IBM_ADMIN/Documents/GitHub/stat101")

```
```{r opts.label = 'interactive', results = 'asis'}
df<-data.frame("name"="Input Data Type","Parent"=NA,"value"=10,"Fac"=2)
df<-rbind(df,setNames(data.frame("Interval","Input Data Type",10,2,stringsAsFactors       = FALSE),names(df)))

df<- rbind(df,setNames(data.frame("Categorical","Input Data Type",10,2, stringsAsFactors       = FALSE),names(df)))
names<-gvisOrgChart(df,options=list(width=600,height=250,
                                    size='large', allowCollapse=TRUE))
plot(names)
```
