---
title       : Statistics-101  
subtitle    : using R
author      : Tuhin Mahmud
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Power 
https://tuhinmahmaud.shinyapps.io/PowerApp/



--- .class #id 

## Central limit Theorem
https://tuhinmahmaud.shinyapps.io/CentralLimitApp/

---  Spearman's p and Pearson's r
```{r echo=FALSE}

X <- data.frame("attributes"=NA,"Pearson'r"=NA,"Spearman's r"=NA)
X[1,1]<-"trend";X[1,2]<-"linear";X[1,3]<-"monotonic"
X[2,1]<-"sampling distribution"; X[2,2]<-"normal"; X[2,3]<-"non normal"
X[3,1]<-"data"; X[3,2]<-"interval";X[3,3]<-"non parametric"
require(xtable)
#require(pander)
#pander(X[1:3,1:3], style = 'grid')
#pander(X[1:3,1:3],style = 'simple', split.cells = Inf)
#set.alignment('left', row.names = 'right')
#panderOptions('table.split.table', Inf)
#pandoc.table(X[1:3,1:3])
```
```{r, results='asis',echo=FALSE}
print(xtable(X[1:3,1:3]), type = "html")
```

--- Choosing a Statistical Test



